name: CI

on:
  push:
  pull_request:

env:
  FORCE_COLOR: 2
  JAVA_VERSION: 11

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          distribution: "adopt"
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ env.JAVA_VERSION }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-${{ env.JAVA_VERSION }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: ./target/data-consumer-*-SNAPSHOT.jar
          if-no-files-found: error
